[project]
name = "explore-mcp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13,<4.0"
dependencies = [
    "fastmcp>=2.13.0.1",
    "psutil>=7.1.2",
    "openai>=2.11.0,<3.0.0",
    "fastapi>=0.124.4",
]
